services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"  # Vite kullanıyorsan
    working_dir: /app
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
